version: '3.8'

services:
  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
    volumes:
      - ./nifi/data:/opt/nifi/nifi-current/data
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ./nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ./nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
    networks:
      - nifi-postgres-net

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: nifi_user
      POSTGRES_PASSWORD: nifi_password
      POSTGRES_DB: nifi_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - nifi-postgres-net

networks:
  nifi-postgres-net:
    driver: bridge
